In [1]:
import random
import ast
import pandas as pd
import numpy as np


def calc_sums(row):
    data = []
    try:
        lst = list(row['prec12'])
        
        for j in range(12):
            d = np.asarray(lst[j*12:j*12+12])
            d = np.where(d == 65535, 0, d)
            d = np.where(d == np.nan, 0, d)
            d = np.where(d < 0, 0, d)
            data.append(np.sum(d))
            
    except:
        data = [0]*12
        
    return data

def avg_height(row):
    h = row['height_dtm']
    h = np.where(h > 1000, np.nan, h)
    if len(h) == 0:
        return np.nan
    return np.nanmean(h)

def avg_height2(row):
    h = row['height_dtm'][10:31,10:31]
    h = np.where(h > 1000, np.nan, h)
    if len(h) == 0:
        return np.nan
    return np.nanmean(h)

def avg_height3(row):
    h = row['height_dtm'][15:26,15:26]
    h = np.where(h > 1000, np.nan, h)
    if len(h) == 0:
        return np.nan
    result = np.nanmean(h)
    if np.isnan(result):
        return 200
    else:
        return result
    
def avg_height4(row):
    h = row['height_dtm'][18:25,18:25]
    h = np.where(h > 1000, np.nan, h)
    if len(h) == 0:
        return np.nan
    result = np.nanmean(h)
    if np.isnan(result):
        return 200
    else:
        return result

def avg_height5(row):
    h = row['height_dtm'][21:22,21:22]
    h = np.where(h > 1000, np.nan, h)
    if len(h) == 0:
        return np.nan
    result = np.nanmean(h)
    if np.isnan(result):
        return 200
    else:
        return result

def count(row):
    h = row['height']
    print(h.shape)
    return np.count_nonzero(h < 1000)

df = pd.read_pickle('test_samples_close_homes250_500.pkl')

df = df.dropna(axis=0)
# df
df = df.drop(['index'], axis=1)
df['prec_sums'] = df.apply(calc_sums, axis=1)
cols = ['sum'+str(i+1) for i in range(12)]
df[cols] = pd.DataFrame(df.prec_sums.tolist(), index=df.index)
df['past3hours'] = df['sum1'] + df['sum2'] + df['sum3']
df = df[(df.past3hours > 1500)]

df['avg_height'] = df.apply(avg_height, axis=1)
df['avg_height2'] = df.apply(avg_height2, axis=1)
df['avg_height3'] = df.apply(avg_height3, axis=1)
df['avg_height4'] = df.apply(avg_height4, axis=1)
df['avg_height5'] = df.apply(avg_height5, axis=1)
# df['count'] = df.apply(count, axis=1)
df

<ipython-input-1-4422d0c1ddaf>:54: RuntimeWarning: Mean of empty slice
  result = np.nanmean(h)
<ipython-input-1-4422d0c1ddaf>:65: RuntimeWarning: Mean of empty slice
  result = np.nanmean(h)

,lat,lng,date,target,prec12,height_dtm,height_dsm,prec_sums,sum1,sum2,...,sum9,sum10,sum11,sum12,past3hours,avg_height,avg_height2,avg_height3,avg_height4,avg_height5
793,51.559414,5.056037,2016-05-22 22:32:49,0,"[4, 0, 9, 13, 36, 27, 4, 7, 11, 14, 18, 14, 11...","[[14.201000213623047, 3.4028234663852886e+38, ...","[[17.37700080871582, 18.194000244140625, 16.96...","[157, 614, 950, 82, 182, 112, 163, 0, 137, 213...",157,614,...,137,213,208,0,1721,14.371545,14.331906,14.316535,14.351135,200.000000
6673,51.556994,5.057451,2016-05-22 22:32:49,1,"[4, 0, 9, 13, 36, 27, 4, 7, 11, 14, 18, 14, 11...","[[14.413000106811523, 14.406999588012695, 14.4...","[[14.413000106811523, 14.4399995803833, 15.149...","[157, 614, 950, 82, 182, 112, 163, 0, 137, 213...",157,614,...,137,213,208,0,1721,14.884939,14.942724,14.993454,15.047794,15.159000
6674,51.560687,5.067502,2016-05-22 22:59:13,1,"[0, 0, 0, 0, 0, 0, 0, 12, 20, 35, 27, 7, 7, 10...","[[14.730999946594238, 14.779000282287598, 14.8...","[[20.513999938964844, 23.503000259399414, 21.4...","[101, 316, 1096, 221, 46, 94, 100, 4, 11, 282,...",101,316,...,11,282,218,8,1513,14.874413,14.870879,14.741732,14.717167,200.000000
794,51.557107,5.068982,2016-05-22 22:59:13,0,"[0, 0, 0, 0, 0, 0, 0, 12, 20, 35, 27, 7, 7, 10...","[[15.07800006866455, 15.121999740600586, 15.17...","[[15.090999603271484, 20.160999298095703, 25.3...","[101, 316, 1096, 221, 46, 94, 100, 4, 11, 282,...",101,316,...,11,282,218,8,1513,15.115528,15.118143,15.096803,15.101355,200.000000
815,50.979267,5.823441,2016-05-27 21:02:33,0,"[4, 5, 6, 7, 5, 5, 5, 5, 5, 4, 2, 2, 2, 3, 7, ...","[[3.4028234663852886e+38, 3.4028234663852886e+...","[[73.45509338378906, 74.81391906738281, 71.321...","[55, 114, 2646, 116, 41, 0, 0, 0, 0, 0, 0, 0]",55,114,...,0,0,0,0,2815,65.916049,65.726647,65.692936,65.723357,65.965034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11741,52.700342,5.288678,2020-08-14 04:20:26,1,"[12, 21, 43, 66, 45, 60, 60, 41, 64, 333, 250,...","[[1.7089999914169312, 3.4028234663852886e+38, ...","[[6.539999961853027, 8.142999649047852, 9.8199...","[1108, 1893, 1629, 440, 282, 0, 0, 0, 0, 0, 0, 0]",1108,1893,...,0,0,0,0,4630,2.041947,2.096906,2.078912,2.320325,200.000000
11743,52.128186,5.899544,2020-08-15 19:43:07,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[67.19954681396484, 66.83068084716797, 66.884...","[[67.56842041015625, 66.89419555664062, 70.735...","[0, 0, 5044, 609, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,...,0,0,0,0,5044,66.856464,66.734647,65.979181,65.620918,65.577972
5858,52.125649,5.902304,2020-08-15 19:43:07,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[61.02631378173828, 61.15302658081055, 3.4028...","[[62.41845703125, 63.77493667602539, 73.517112...","[0, 0, 4212, 339, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,...,0,0,0,0,4212,61.664783,62.606066,63.302027,63.743886,64.568634
11744,50.810105,5.931416,2020-08-16 13:34:32,1,"[3, 25, 33, 99, 152, 21, 12, 0, 0, 46, 0, 0, 0...","[[101.04278564453125, 101.07867431640625, 101....","[[101.04278564453125, 101.07867431640625, 101....","[391, 0, 5013, 157, 0, 0, 0, 0, 0, 0, 0, 0]",391,0,...,0,0,0,0,5404,105.217469,105.314269,105.329428,105.786193,105.995796
5859,50.811039,5.925671,2020-08-16 13:34:32,0,"[3, 25, 33, 99, 152, 21, 12, 0, 0, 46, 0, 0, 0...","[[110.85908508300781, 110.86576080322266, 110....","[[110.85908508300781, 110.86576080322266, 110....","[391, 0, 5013, 157, 0, 0, 0, 0, 0, 0, 0, 0]",391,0,...,0,0,0,0,5404,101.480237,99.923325,99.785431,100.177045,200.000000

In [2]:
# df1 = (df[df.target==1])
# df0 = (df[df.target==0])
# # df0 = df0.sample(len(df1))
# df = pd.concat([df0, df1])
# # values = list(df[df.target==0]['past3hours'])
# # len(values)

def get_flow(data):
    dtm = data['height_dtm']
    dsm = data['height_dsm']
    
    #water
    dtm[dsm>1000] = -100
    
    amount_of_water = dtm.shape[0] * dtm.shape[1]
    building_count = np.sum(dtm>1000)
    amount_of_rain_per_cell = amount_of_water/(amount_of_water-building_count)/1000
    
    # simple alg
    result = np.full(dtm.shape, 0.0)
    for i in range(60):
        if i < 20:
            result[dtm<1000] += amount_of_rain_per_cell
            
        for x in range(1, dtm.shape[1]-1):
            for y in range(1, dtm.shape[0]-1):
                if dtm[y,x] < 1000:
                    val = dtm[y,x]
                    waterval = result[y,x]


                    topdiff = val+waterval-dtm[y+1,x]+result[y+1,x]
                    bottomdiff = val+waterval-dtm[y-1,x]+result[y-1,x]
                    leftdiff = val+waterval-dtm[y,x-1]+result[y,x-1]
                    rightdiff = val+waterval-dtm[y,x+1]+result[y,x+1]
                    water_to_move = min(waterval, max([topdiff, bottomdiff, leftdiff, rightdiff]))
                    total = 0
                    if topdiff > 0:
                        total+=topdiff

                    if leftdiff > 0:
                        total+=leftdiff

                    if rightdiff > 0:
                        total+=rightdiff

                    if bottomdiff > 0:
                        total+=bottomdiff

                    if topdiff > 0:
                        result[y+1,x] += (topdiff/total) * water_to_move

                    if leftdiff > 0:
                        result[y,x-1] += (leftdiff/total) * water_to_move

                    if rightdiff > 0:
                        result[y,x+1] += (rightdiff/total) * water_to_move

                    if bottomdiff > 0:
                        result[y-1,x] += (bottomdiff/total) * water_to_move

                    if total > 0:
                        result[y,x] -= water_to_move
                    
    result[dsm>1000] = 0
    return result


df['rain_flow'] = df.apply(get_flow, axis=1)

In [3]:
def makeheightsmaller(row):
    t = row['rain_flow'][15:26,15:26]
    t = t.flatten()
    return t

def get_element(row, n):
    return row['rain_flow2'][n]

df['rain_flow2'] = df.apply(makeheightsmaller, axis=1)

rainflow_cols = []
for h in range(120):
    name = 'h_{}'.format(h)
    rainflow_cols.append(name)
    df[name] = df.apply(get_element, axis=1, args=(h,))

df

,lat,lng,date,target,prec12,height_dtm,height_dsm,prec_sums,sum1,sum2,...,h_110,h_111,h_112,h_113,h_114,h_115,h_116,h_117,h_118,h_119
793,51.559414,5.056037,2016-05-22 22:32:49,0,"[4, 0, 9, 13, 36, 27, 4, 7, 11, 14, 18, 14, 11...","[[14.201000213623047, 3.4028234663852886e+38, ...","[[17.37700080871582, 18.194000244140625, 16.96...","[157, 614, 950, 82, 182, 112, 163, 0, 137, 213...",157,614,...,0.092429,0.088640,0.077237,0.078006,0.051162,0.049653,0.047520,0.049906,0.042329,0.048282
6673,51.556994,5.057451,2016-05-22 22:32:49,1,"[4, 0, 9, 13, 36, 27, 4, 7, 11, 14, 18, 14, 11...","[[14.413000106811523, 14.406999588012695, 14.4...","[[14.413000106811523, 14.4399995803833, 15.149...","[157, 614, 950, 82, 182, 112, 163, 0, 137, 213...",157,614,...,0.027092,0.006749,0.000322,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000661
6674,51.560687,5.067502,2016-05-22 22:59:13,1,"[0, 0, 0, 0, 0, 0, 0, 12, 20, 35, 27, 7, 7, 10...","[[14.730999946594238, 14.779000282287598, 14.8...","[[20.513999938964844, 23.503000259399414, 21.4...","[101, 316, 1096, 221, 46, 94, 100, 4, 11, 282,...",101,316,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.006388,0.024005,0.023948,0.012737,0.012389
794,51.557107,5.068982,2016-05-22 22:59:13,0,"[0, 0, 0, 0, 0, 0, 0, 12, 20, 35, 27, 7, 7, 10...","[[15.07800006866455, 15.121999740600586, 15.17...","[[15.090999603271484, 20.160999298095703, 25.3...","[101, 316, 1096, 221, 46, 94, 100, 4, 11, 282,...",101,316,...,0.000000,0.000000,0.000000,0.000019,0.000251,0.000000,0.000000,0.000000,0.000000,0.000000
815,50.979267,5.823441,2016-05-27 21:02:33,0,"[4, 5, 6, 7, 5, 5, 5, 5, 5, 4, 2, 2, 2, 3, 7, ...","[[3.4028234663852886e+38, 3.4028234663852886e+...","[[73.45509338378906, 74.81391906738281, 71.321...","[55, 114, 2646, 116, 41, 0, 0, 0, 0, 0, 0, 0]",55,114,...,0.000000,0.000000,0.000219,0.000254,0.000000,0.000000,0.003773,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11741,52.700342,5.288678,2020-08-14 04:20:26,1,"[12, 21, 43, 66, 45, 60, 60, 41, 64, 333, 250,...","[[1.7089999914169312, 3.4028234663852886e+38, ...","[[6.539999961853027, 8.142999649047852, 9.8199...","[1108, 1893, 1629, 440, 282, 0, 0, 0, 0, 0, 0, 0]",1108,1893,...,0.000481,0.016189,0.000000,0.000000,0.000000,0.000000,0.001997,0.000000,0.000000,0.000000
11743,52.128186,5.899544,2020-08-15 19:43:07,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[67.19954681396484, 66.83068084716797, 66.884...","[[67.56842041015625, 66.89419555664062, 70.735...","[0, 0, 5044, 609, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,...,0.000000,0.000000,0.001373,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5858,52.125649,5.902304,2020-08-15 19:43:07,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[61.02631378173828, 61.15302658081055, 3.4028...","[[62.41845703125, 63.77493667602539, 73.517112...","[0, 0, 4212, 339, 0, 0, 0, 0, 0, 0, 0, 0]",0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11744,50.810105,5.931416,2020-08-16 13:34:32,1,"[3, 25, 33, 99, 152, 21, 12, 0, 0, 46, 0, 0, 0...","[[101.04278564453125, 101.07867431640625, 101....","[[101.04278564453125, 101.07867431640625, 101....","[391, 0, 5013, 157, 0, 0, 0, 0, 0, 0, 0, 0]",391,0,...,0.000003,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5859,50.811039,5.925671,2020-08-16 13:34:32,0,"[3, 25, 33, 99, 152, 21, 12, 0, 0, 46, 0, 0, 0...","[[110.85908508300781, 110.86576080322266, 110....","[[110.85908508300781, 110.86576080322266, 110....","[391, 0, 5013, 157, 0, 0, 0, 0, 0, 0, 0, 0]",391,0,...,0.198139,0.057731,0.000002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [27]:
from catboost import Pool, cv


def max_rainflow(row):
    return np.max(row['rain_flow'][15:26,15:26])

def min_rainflow(row):
    return np.min(row['rain_flow'][15:26,15:26])

def avg_rainflow(row):
    return np.mean(row['rain_flow'][18:23,18:23])
    


df['avg_rainflow'] = df.apply(avg_rainflow, axis=1)
df['max_rainflow'] = df.apply(max_rainflow, axis=1)
df['min_rainflow'] = df.apply(min_rainflow, axis=1)

df = df.dropna()
# cols+['avg_height', 'avg_height2', 'avg_height3', 'avg_height4', 'avg_height5', 
train_data = df[['avg_rainflow', 'max_rainflow']]

train_labels = df['target']

# cv_dataset = Pool(data=train_data,
#                   label=train_labels)

# params = {"iterations": 1000,
#           "depth": 10,
#           "loss_function": "Logloss",
#           "verbose": True,
#         "custom_metric": ["F1", "BalancedAccuracy", "Recall", "Precision"]}

# scores = cv(cv_dataset,
#             params,
#             fold_count=2, 
#             plot="True")


df.sort_values('date', ignore_index=True)[['target', 'date','avg_height', 'avg_height2', 'avg_height3', 'avg_height4', 'avg_height5', 'max_rainflow', 'avg_rainflow']].to_csv('test.csv')
df.sort_values('date', ignore_index=True)
df.groupby('target').agg({'past3hours': ['mean'], 'max_rainflow':['mean', 'std'], 'avg_rainflow':['mean', 'std']})

         past3hours max_rainflow           avg_rainflow
               mean         mean       std         mean       std
target
0       2832.427536     0.206262  0.173968     0.010467  0.012618
1       2843.757685     0.241345  0.195092     0.014553  0.018349

In [29]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score


for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(train_data, train_labels, test_size=0.2)

    # fit model no training data
    model = XGBClassifier()
    model.fit(X_train, y_train)


    y_pred = model.predict(X_test)
    predictions = [round(value) for value in y_pred]
    accuracy = accuracy_score(y_test, predictions)
    print("Accuracy: %.2f%%" % (accuracy * 100.0))

/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[17:55:46] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Accuracy: 49.77%
[17:55:46] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

Accuracy: 50.23%
[17:55:46] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Accuracy: 55.20%
[17:55:46] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

Accuracy: 54.30%
[17:55:46] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Accuracy: 52.94%
[17:55:46] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

Accuracy: 53.39%
[17:55:46] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Accuracy: 50.23%
[17:55:46] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(
/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

Accuracy: 55.20%
[17:55:46] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Accuracy: 55.66%
[17:55:47] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Accuracy: 49.77%

/Users/thijssimons/Documents/projects/wateroverlast/venv/lib/python3.8/site-packages/xgboost/data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(